language: node_js
node_js:
    - 5
    - 6
env:
    - NODE_ENV=test CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success: cat ./coverage/lcov.info | coveralls
