# Site settings
title: Nekochat
description: NekoRPG Web Chat System.
baseurl: "/nekochat"
url: "https://ukatama.github.io"

twitter_username: y_ukatama
github_username:  ukatama

repository: ukatama/nekochat

# Build settings
markdown: kramdown
