name: nekochat
app:
    guest: true
    livereload: false
    secret: secret!!
browser:
    debug: false
    feedback_form: https://docs.google.com/forms/d/1i3zWclkL6aY2mtqBC4EQhErGQaxWvGn84oUVHcE2S0w/viewform
database:
    default:
        client: sqlite3
        connection:
            filename: tmp/db.sqlite
    session:
        client: sqlite3
        connection:
            filename: tmp/db.sqlite
redis:
    host: localhost
server:
    host: localhost
    port: 8000
session:
    store: database
    resave: true
    saveUninitialized: true
data_cleaner:
    file:
        enabled: true
        interval: PT1H
        soft: P7D
        hard: P14D
    room:
        enabled: false
        interval: PT1H
        soft: P14D
        hard: P21D
file:
    types:
        - image/*
        - audio/*
    maxSize: 512M
