name: nekochat
app:
    guest: true
    livereload: false
browser:
    debug: false
database:
    default:
        client: sqlite3
        connection:
            filename: tmp/db.sqlite
    session:
        client: sqlite3
        connection:
            filename: tmp/db.sqlite
redis:
    host: localhost
server:
    host: localhost
    port: 8000
session:
    store: database
    resave: true
    saveUninitialized: true
